### ISSUE TITLE
Add support for IDA 6.9

### ISSUE THREAD

**Issue by kvozon** [ynvb/DIE#28]
Hello, I'm trying to run it on ida 6.9, but got an error of QDialog on AboutWindow, after i fix it with QWidget, i got an log message output of parsers loaded and nothing else -  menu item doesn't appears. Can you please fix it?

**Comment by hardboost** [comment]
@kvozon can you check fix? https://github.com/ynvb/DIE/pull/29

**Comment by waadaa85** [comment]
DIE failed to initialize on IDA Pro 6.95 (32 bits)... 

I got the following:
die_proxy.py: global name 'idaapi' is not defined
Traceback (most recent call last):
  File "D:\IDA695\python\ida_idaapi.py", line 509, in IDAPython_ExecScript
    execfile(script, g)
  File "D:/IDA695/plugins/die_proxy.py", line 13, in <module>
    plugin = imp.load_source(__name__, plugin_path)
  File "D:\IDA695\DIE\DIE.py", line 24, in <module>
    import DIE.UI.BPView
  File "D:\IDA695\DIE\DIE\UI\BPView.py", line 5, in <module>
    from DIE.Lib import BpHandler
  File "D:\IDA695\DIE\DIE\Lib\BpHandler.py", line 546, in <module>
    _bp_handler = BpHandler()
  File "D:\IDA695\DIE\DIE\Lib\BpHandler.py", line 36, in __init__
    self.iat = StaticImports()              # Static IAT
  File "D:\IDA695\DIE\DIE\Lib\DbgImports.py", line 24, in __init__
    self.get_iat_data()
  File "D:\IDA695\DIE\DIE\Lib\DbgImports.py", line 42, in get_iat_data
    imp_num = idaapi.get_import_module_qty()  # Number of imported modules
NameError: global name 'idaapi' is not defined

additional infos:
DIE installed from Github cloned dir.
Python is 2.7.12 from Anaconda.
pip install -r requirements.txt has been done.
pywin32 installed (provided by anaconda) 
%pythonpath% has both IDAPro root dir and IDA's Python sub-directory
%PATH% also has both repositories
%DIEDIR% exists and point to D:\IDA695\DIE 

Please advise.
