### ISSUE TITLE
IDA 7.0: Function View is always empty.

### ISSUE THREAD

**Issue by bittlejoo** [ynvb/DIE#37]
When I select "All threads" or any other thread in "Thread" combobox, I always get this error and nothing happens (function view stay empty).

> Traceback (most recent call last):
>   File "D:\DIE\DIE\UI\FunctionViewEx.py", line 907, in on_thread_combobox_change
>     self.reset_function_count(thread_id)  # reset function count according to currently selected thread
>   File "D:\DIE\DIE\UI\FunctionViewEx.py", line 626, in reset_function_count
>     rows = root_item.rowCount()
> AttributeError: 'NoneType' object has no attribute 'rowCount'

**Comment by ynvb** [comment]
Thanks for opening the issue, taking a deeper look into that.

**Comment by bittlejoo** [comment]
I have tested an older version of the plugin (with PySide, not PyQt5) in IDA 6.8 and exception is still shown, but Function View lists all hooked functions correctly. It seems that the problem is not in the Function View at all, but somewhere deeper with the plugin. When I try to "Debug entire code" or "Debug a custom scope", I see breakpoints are placed, but "Exceptions", "Functions" and "Value" views don't reflect any info during and after debugging session. Looks like DIE is just not logging any function calls.

Later I discovered many errors in DIE.log, I will attach it to this post.
All Path variables are set correctly for IDA and Python.

I will stay with IDA 6.8 + Python 2.7 32-bit for now, DIE works fine with them. 

[DIE.log](https://github.com/ynvb/DIE/files/3586607/DIE.log)
