### ISSUE TITLE
IDA 7.7 not work 😰

### ISSUE THREAD

**Issue by steve007iii** [ynvb/DIE#42]
One of my favorite plugins when upgrading my (IDA) I realized that it doesn't run on 7.7
there is no problem with dependencies

I think the fixes are too small for it to run on 7.7 and I don't have any Phytom knowledge to do anything.

IDA 7.7
python-3.10.5

pip3 install -U git+https://github.com/tmr232/Sark.git#egg=Sark

<img src="https://i.imgur.com/t5WFzY8.png">

<img src="https://i.imgur.com/5G6CaVi.png">

```
`C:\Isolation\IDA _7.7\plugins\DIE.py: (unicode error) 'unicodeescape' codec can't decode bytes in position 4-5: truncated \UXXXXXXXX escape (C:/Isolation/IDA _7.7/plugins/DIE.py, line 326)
Traceback (most recent call last):
  File "C:\Isolation\IDA _7.7\python\3\ida_idaapi.py", line 579, in IDAPython_ExecScript
    code = compile(raw.decode(encoding), path, 'exec')
  File "C:/Isolation/IDA _7.7/plugins/DIE.py", line 326
    self.add_menu_item_helper("DIE:markexecutionflow", "Mark\Unmark Execution Flow",
                                                                                   ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 4-5: truncated \UXXXXXXXX escape

C:\Isolation\IDA _7.7\plugins\die_proxy.py: (unicode error) 'unicodeescape' codec can't decode bytes in position 4-5: truncated \UXXXXXXXX escape (DIE.py, line 326)
Traceback (most recent call last):
  File "C:\Isolation\IDA _7.7\python\3\ida_idaapi.py", line 580, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Isolation/IDA _7.7/plugins/die_proxy.py", line 13, in <module>
    plugin = imp.load_source(__name__, plugin_path)
  File "C:\Python310\Lib\imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 619, in _exec
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Isolation\IDA _7.7\plugins\DIE.py", line 326
    self.add_menu_item_helper("DIE:markexecutionflow", "Mark\Unmark Execution Flow",
                                                                                   ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 4-5: truncated \UXXXXXXXX escape`
```

c++ or java can i do something? but python i have no idea!

**Comment by tmr232** [comment]
didn't have time to check this yet - but it looks like an extra `\` (`"Mark\\Unmark"`) would solve this one. That said - there may be more issues, as I don't think DIE is currently Python3 compatible.

**Comment by steve007iii** [comment]
Too bad it still has more bugs, but at least your recommendation fixed something...😢
I think we would have to wait for a Python3 compatible solution.
**This breaks my heart because maybe this is for a long time.**


`Please check the Edit/Plugins menu for more information.
C:\Isolation\IDA _7.7\plugins\DIE.py: No module named 'cStringIO'
Traceback (most recent call last):
  File "C:\Isolation\IDA _7.7\python\3\ida_idaapi.py", line 580, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Isolation/IDA _7.7/plugins/DIE.py", line 2, in <module>
    from awesome.context import ignored
  File "C:\Python310\Lib\site-packages\awesome\context.py", line 4, in <module>
    from cStringIO import StringIO
ModuleNotFoundError: No module named 'cStringIO'`

**Comment by steve007iii** [comment]
> didn't have time to check this yet - but it looks like an extra `\` (`"Mark\\Unmark"`) would solve this one. That said - there may be more issues, as I don't think DIE is currently Python3 compatible.

Too bad it still has more bugs, but at least your recommendation fixed something...😢
I think we would have to wait for a Python3 compatible solution.
This breaks my heart because maybe this is for a long time.

`Please check the Edit/Plugins menu for more information. C:\Isolation\IDA _7.7\plugins\DIE.py: No module named 'cStringIO' Traceback (most recent call last): File "C:\Isolation\IDA _7.7\python\3\ida_idaapi.py", line 580, in IDAPython_ExecScript exec(code, g) File "C:/Isolation/IDA _7.7/plugins/DIE.py", line 2, in <module> from awesome.context import ignored File "C:\Python310\Lib\site-packages\awesome\context.py", line 4, in <module> from cStringIO import StringIO ModuleNotFoundError: No module named 'cStringIO`
